### PR TITLE
(BUG) Negotiation fails for servers where 'NTLMv2 session security' i…

### PR DESCRIPTION
**Pull request by davejohnston**
Negotiation fails for servers where 'NTLMv2 session security' is required.

If a server has specified that  NTLMv2 session security is required,
then negotiation will fail as the client does not advertise this during
the handshake.    The negoiate message needs to include the relevant
flag 'negotiateFlagNTLMSSPNEGOTIATEEXTENDEDSESSIONSECURITY'

To test enable this on the remote server by using regedt32 to modify the
key
HKLM\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0\NtlmMinServerSec and
set the value to 0x20080000

### CODE REVIEW

**Comment by boumenot** [comment]
/cc @paulmey 

LGTM. CI is failing, but that is unrelated to this change.

**Comment by davejohnston** [comment]
If anyone has permissions to kick the build of again that would be great.

**Comment by boumenot** [comment]
Please rebase your PR, and re-submit. This will pick up the CI fix.

**Comment by davejohnston** [comment]
@boumenot done.  It looks good now.  Cheers

**Comment by boumenot** [comment]
Thanks for sticking with us, and the contribution!

**Pull request merged**
